### ISSUE TITLE
When editing the icons, add a grid for better scale options

### ISSUE THREAD

**Issue by anrihaglund** [csiqueirasilva/poe-skills-overlay#2]
My OCD goes crazy when I'm unable to line up the icons perfectly. If it's possible, a grid with the ability to fill one or more fields (just as the alternative way of resizing, and you'd be able to widen squares into 1, 4, 9 grid fields etc. ) would be perfect.

**Comment by csiqueirasilva** [comment]
Thanks for bringing this up. For now, you can try using the keyboard arrows to line those pixels perfectly while the configure menu is up for an icon.

If you can post an illustration to your idea it would be perfect, since a text description can generate some noise between what you typed and what I understood from it.

**Comment by anrihaglund** [comment]
[](https://imgur.com/a/hkvlZvU)
The grid can obviously be tighter, allowing for more size manipulation. The icons can be expanded only along the grid field borders. The grid should be another option toggleable in the top right corner with the other options.

**Comment by anrihaglund** [comment]
https://imgur.com/a/hkvlZvU

The grid can be tighter to allow for more size manipulation. The grid should be option toggleable in the top right corner together with other options. The icons can be only expanded along the grid field borders.

**Comment by csiqueirasilva** [comment]
> https://imgur.com/a/hkvlZvU

its an interesting concept for a next release.

What about the grid size? 

- Multiples of what the game's UI icon offer
Problem is that it would be like 1 square, 4 squares, 16 squares ... screen would be filled very quickly.

- Configurable
Add a grid of x pixels by x pixels size (maybe in the config file or as a prompt form field).

**Comment by anrihaglund** [comment]
If you'd be able to make it configurable (to a certain extend obviously) then it would be super cool.

**Comment by csiqueirasilva** [comment]
Hello @anrihaglund . It is done, with the gridsize being configurable in the settings json file (check readme for additional information). There are some other features too. Release tag is v1.0-rc4

If you find any bugs or other stuff, please open a new issue.
