### ISSUE TITLE
Overlay display black squares

### ISSUE THREAD

**Issue by Mwoua** [csiqueirasilva/poe-skills-overlay#4]
Hi,
I have just tried the overlay, but I have black square instead of the actual image of the skill or flask (see attached screenshot).
![Black_Box_Bug](https://user-images.githubusercontent.com/7242471/93732283-a4697280-fb9e-11ea-81fc-1b7993e2db1e.jpg)

You can see on the screenshot that the two top square are not entirely black, so maybe they actually capture something

Im on windows 10, only have one screen, my resolution is 3440*1440 and a Nvidia GTX 1060

**Comment by csiqueirasilva** [comment]
it seems to really be an issue with the resolution. send me your discord info so i can guide you better on how to debug this, if youd like. email is csiqueirasilva@gmail.com

**Comment by Mwoua** [comment]
Mwoua#1743
